app:
  name: "metric-index"
  mode: "prod"
  port: 7001

log:
  level: "debug"
  filename: "logs/metric-index.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host:
  port:
  user:
  password:
  dbname: "metric-index"
  max_open_conns: 200
  max_idel_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 3000

metric_filter:
  metricNameRegex: ".*"
  metricValueRegex: ".*"
  labelNameRegex: ".*"
  labelValueRegex: ".*"

metric_store:
  cache:
    isexpire: true
    expire: 604800
    defaultExpire: 604800
    cleanupInterval: 600
    dist_interval: 172800
    worker_num: 100
    flush_lens: 1000
    flush_interval: 10
  store:
    url:
      - "http://elasticsearch-host:9200"
    username:
    password:
    index_name: "metric-test"
    worker_num: 50
    flush_bytes: 5242880
    flush_interval: 10

remote:
  write:
    url: "http://vminsert-host:8480/insert/1/prometheus/api/v1/write"
    content_type: "application/x-protobuf"
  send:
    url: "http://vminsert-host:4242/insert/1/opentsdb/api/put"
    content_type: "application/json"